{{- if .Values.global.privateAccess.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: finops-private-access
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "finops.labels" . | nindent 4 }}
spec:
  basicAuth:
    secret: {{ .Values.global.basicAuthSecretName }}
    removeHeader: true
{{- end }}
