apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "finops.fullname" . }}-watchlist
  labels:
    {{- include "finops.labels" . | nindent 4 }}
    app.kubernetes.io/component: watchlist
data:
  watchlist.json: |
    {{- toPrettyJson .Values.watchlist | nindent 4 }}

